<?php

namespace App\Enums;

/**
 * Journal voucher classification (M13).
 */
enum VoucherType: string
{
    case Journal = 'journal';
    case Sales = 'sales';
    case Purchase = 'purchase';
    case Receipt = 'receipt';
    case Payment = 'payment';
    case Contra = 'contra';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }

    public function label(): string
    {
        return match ($this) {
            self::Journal => 'Journal',
            self::Sales => 'Sales',
            self::Purchase => 'Purchase',
            self::Receipt => 'Receipt',
            self::Payment => 'Payment',
            self::Contra => 'Contra',
        };
    }

    /**
     * Vouchers generated by the system from source documents cannot be edited by hand.
     */
    public function isSystemGenerated(): bool
    {
        return in_array($this, [self::Sales, self::Purchase], true);
    }
}
